#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 01 20:35:19 CST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
